name: Download photo and add to repo

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: America/New_York
      - name: Check out this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download photo and add to repo
        run: |
            NAME=`date +"%Y-%m-%d %H:%M:%S.jpg"`
            DATAPATH=`date +"data/%Y/%m/%d"`
            URL="https://webcams.nyctmc.org/api/cameras/f801cf2f-cd02-4077-aa53-99ee8a00e1ab/image"
            mkdir -p $DATAPATH
            curl -s -o "$DATAPATH/$NAME" $URL
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
